# Generated by Django 5.2.12 on 2026-08-31 13:25

import apps.referentiel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifiant stable, repris à l'import pour mettre à jour plutôt que dupliquer.", max_length=80, unique=True, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('version', models.CharField(blank=True, help_text="Version du référentiel chez son auteur, telle qu'il la nomme.", max_length=40, verbose_name='Version')),
                ('source', models.CharField(blank=True, help_text="D'où vient ce référentiel : organisme, document, URL.", max_length=300, verbose_name='Source')),
                ('libelles_de_niveaux', models.JSONField(blank=True, default=list, validators=[apps.referentiel.models.valider_libelles_de_niveaux], verbose_name='Libellés des trois niveaux')),
                ('est_actif', models.BooleanField(default=False, help_text="Un seul référentiel actif à la fois : c'est celui que l'interface affiche.", verbose_name='Actif')),
                ('importe_le', models.DateTimeField(auto_now=True, verbose_name='Importé le')),
            ],
            options={
                'verbose_name': 'Référentiel',
                'verbose_name_plural': 'Référentiels',
                'ordering': ['intitule'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('est_actif', True)), fields=('est_actif',), name='un_seul_referentiel_actif')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage ; à défaut, l'ordre alphabétique du code.", verbose_name='Ordre')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='referentiel.referentiel', verbose_name='Référentiel')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='referentiel.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre', 'code'],
                'constraints': [models.UniqueConstraint(fields=('module', 'code'), name='code_de_competence_unique_par_module')],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('referentiel', 'code'), name='code_de_module_unique_par_referentiel'),
        ),
    ]
