# Generated by Django 5.2.12 on 2026-08-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(help_text='Date locale du serveur ; le compteur repart à zéro à minuit.', verbose_name='jour de consommation')),
                ('generations', models.PositiveIntegerField(default=0, verbose_name='générations consommées')),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Vide pour les générations demandées par l'API du service IA (C9), dont les consommateurs sont des programmes porteurs d'une clé de service et non des apprenants inscrits.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consommations_journalieres', to=settings.AUTH_USER_MODEL, verbose_name='apprenant')),
            ],
            options={
                'verbose_name': 'consommation journalière',
                'verbose_name_plural': 'consommations journalières',
                'ordering': ['-jour', 'utilisateur'],
                'indexes': [models.Index(fields=['jour'], name='idx_consommation_jour')],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'jour'), name='une_consommation_par_personne_et_par_jour'), models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', True)), fields=('jour',), name='une_consommation_service_ia_par_jour')],
            },
        ),
    ]
