# Generated by Django 5.2.4 on 2025-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='exercisesubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AlterModelOptions(
            name='userexerciseprogress',
            options={'verbose_name': 'Exercise progress', 'verbose_name_plural': 'Exercise progress'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(default='# Your code here\n'),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
    ]
