# Generated by Django 5.2.12 on 2026-08-31 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_supprime_ip_address'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='referentiel.competence', verbose_name='Compétence visée'),
        ),
    ]
