# Generated by Django 5.2.4 on 2025-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('explanation', 'Explanation'), ('examples', 'Examples'), ('summary', 'Summary'), ('advanced', 'Advanced')], max_length=50),
        ),
    ]
