# Generated by Django 5.2.12 on 2026-09-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_and_more'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDApprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='referentiel.competence', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': "Fiche d'apprenant",
                'verbose_name_plural': "Fiches d'apprenant",
                'ordering': ['-modifie_le'],
                'unique_together': {('apprenant', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='AjoutDeFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="La question ou l'action qui a produit cet ajout.", max_length=300, verbose_name="Question d'origine")),
                ('origine', models.CharField(choices=[('a_la_demande', "Demandé par l'apprenant"), ('parcours', 'Proposé par le parcours'), ('montee_de_niveau', 'Montée de niveau')], default='a_la_demande', max_length=20, verbose_name='Origine')),
                ('section_visee', models.CharField(blank=True, help_text="Titre de la section du cours à laquelle l'ajout répondait.", max_length=200, verbose_name='Section visée')),
                ('niveau_vise', models.PositiveSmallIntegerField(blank=True, help_text='Renseigné pour une montée de niveau, nul sinon.', null=True, verbose_name='Niveau visé')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('sources', models.JSONField(blank=True, default=list, help_text='url_source, code_licence et attribution_requise par fragment.', verbose_name='Sources')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajouts', to='courses.fichedapprenant', verbose_name='Fiche')),
            ],
            options={
                'verbose_name': 'Ajout de fiche',
                'verbose_name_plural': 'Ajouts de fiche',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CoursDeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('publie', "Publié par l'organisme"), ('provisoire', 'Provisoire, engendré par le modèle')], max_length=12, verbose_name='Statut')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Fragments du corpus employés, avec leur licence.', verbose_name='Sources')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('remplace_le', models.DateTimeField(blank=True, help_text="Daté quand un cours publié prend la place d'un provisoire.", null=True, verbose_name='Remplacé le')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_de_reference', to='referentiel.competence', verbose_name='Compétence')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par')),
            ],
            options={
                'verbose_name': 'Cours de référence',
                'verbose_name_plural': 'Cours de référence',
                'ordering': ['competence__code', '-cree_le'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('remplace_le__isnull', True)), fields=('competence', 'statut'), name='un_seul_cours_actif_par_competence_et_statut')],
            },
        ),
    ]
