# Generated by Django 5.2.12 on 2026-09-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_fichedapprenant_ajoutdefiche_coursdereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursdereference',
            name='contenu',
        ),
        migrations.CreateModel(
            name='PartieDeCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('fichier_source', models.CharField(help_text='Nom du support markdown dont cette partie provient.', max_length=200, verbose_name="Fichier d'origine")),
                ('sous_module', models.CharField(help_text="Sous-module du corpus déclaré par le fichier d'index.", max_length=80, verbose_name='Sous-module')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='courses.coursdereference', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Partie de cours',
                'verbose_name_plural': 'Parties de cours',
                'ordering': ['cours', 'ordre'],
                'unique_together': {('cours', 'ordre')},
            },
        ),
    ]
