# Generated by Django 5.2.12 on 2026-09-12 13:56

from django.db import migrations


class Migration(migrations.Migration):
    """
    Retire `CourseSection`, modèle jamais écrit ni lu.

    Compétence visée : C4 (épreuve E1), C17 (E4)

    La table était vide au moment de la migration (vérifié : 0 ligne), et
    `course.sections` n'apparaissait dans aucune vue ni aucun gabarit. Le
    découpage des cours est porté par `PartieDeCours`, rattachée au cours de
    référence.

    La suppression est donc sans perte de données. Elle retire une table, une
    clé étrangère vers `Course` et une contrainte d'unicité qui décrivaient un
    dispositif inexistant.
    """


    dependencies = [
        ('courses', '0005_remove_coursdereference_contenu_partiedecours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
