# Generated by Django 5.2.4 on 2025-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('starting', 'Starting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
