# Generated by Django 5.2.12 on 2026-09-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_gameroom_status'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier signe de vie'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles_de_quiz', to='referentiel.competence', verbose_name='Compétence visée'),
        ),
    ]
