# Generated by Django 5.2.4 on 2025-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_kodauser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodauser',
            name='koda_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
