# Generated by Django 5.2.4 on 2025-07-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kodauser_koda_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodauser',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kodauser',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kodauser',
            name='total_courses_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kodauser',
            name='total_quizzes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kodauser',
            name='total_study_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
