# Generated by Django 5.2.4 on 2025-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_kodauser_current_streak_kodauser_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodauser',
            name='koda_avatar',
            field=models.CharField(blank=True, default='koda_base.png', max_length=100, null=True),
        ),
    ]
