# Generated by Django 5.2.12 on 2026-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodauser',
            name='animation_koda',
            field=models.BooleanField(default=True, help_text="Anime le personnage du tuteur. Décocher fige Koda sur une image. Le réglage « mouvement réduit » du système est respecté quoi qu'il arrive : ce champ permet de figer l'animation sans y toucher.", verbose_name='Animer Koda'),
        ),
    ]
