# Generated by Django 5.2.12 on 2026-08-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='referentiel.competence', verbose_name='Compétence visée'),
        ),
        migrations.AddField(
            model_name='usermistake',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs', to='referentiel.competence', verbose_name='Compétence visée'),
        ),
    ]
