"""
Django settings for eduai_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "apps"))

# Chargement des variables d'environnement avant toute lecture de réglage.
# Jusqu'ici, load_dotenv() n'était appelé que dans apps/agents/tools/llm_loader.py,
# donc les réglages Django ne pouvaient pas lire le fichier .env.
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Compétence visée : C13 (épreuve E3) — sécurité de l'application
#
# Choix : lecture depuis l'environnement, sans valeur de repli. Motivation :
# la clé était jusqu'ici écrite en dur dans ce fichier, donc versionnée et
# lisible par quiconque ouvre le dépôt. Une valeur de repli dans le code
# reproduirait exactement le problème, en le rendant seulement moins visible.
# La clé versionnée a été révoquée : celle qui est en service a été
# régénérée et ne vit que dans .env, ignoré par Git.
#
# L'absence de la variable interrompt le démarrage plutôt que de laisser
# l'application tourner avec une clé devinable — une signature de session
# forgée permettrait de se faire passer pour n'importe quel apprenant.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY est absente de l'environnement. "
        "La renseigner dans le fichier .env à la racine du projet "
        "(voir .env.example). Générer une valeur avec : "
        "uv run python -c \"from django.core.management.utils import "
        "get_random_secret_key as g; print(g())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Logging for debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app']

CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'apps.users',
    'apps.courses',
    'apps.quiz',
    'apps.revision',
    'apps.agents',
    'apps.chat',
    'apps.rag',
    'apps.tracker',
    'apps.exercises',
    'theme',

    # Third-party apps
    'tailwind',
    'rest_framework',
    'django_browser_reload',
    'channels',
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'eduai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'eduai_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.KodaUser"

# Custom authentication backend
AUTHENTICATION_BACKENDS = [
    'apps.users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Authentication redirect URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/courses/generator/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Toujours défini pour collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Always defined for collectstatic

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Folder for global static files
]

# Static file finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files (User-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'    
LOGOUT_REDIRECT_URL = '/auth/login/'
LOGIN_URL = '/auth/login/'            # @login_required protection

# Channels configuration
ASGI_APPLICATION = 'eduai_project.asgi.application'

# WebSocket configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Channel layers configuration for WebSockets