"""
Django settings for eduai_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "apps"))

# Chargement des variables d'environnement avant toute lecture de réglage.
# Jusqu'ici, load_dotenv() n'était appelé que dans apps/agents/tools/llm_loader.py,
# donc les réglages Django ne pouvaient pas lire le fichier .env.
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Compétence visée : C13 (épreuve E3) — sécurité de l'application
#
# Choix : lecture depuis l'environnement, sans valeur de repli. Motivation :
# la clé était jusqu'ici écrite en dur dans ce fichier, donc versionnée et
# lisible par quiconque ouvre le dépôt. Une valeur de repli dans le code
# reproduirait exactement le problème, en le rendant seulement moins visible.
# La clé versionnée a été révoquée : celle qui est en service a été
# régénérée et ne vit que dans .env, ignoré par Git.
#
# L'absence de la variable interrompt le démarrage plutôt que de laisser
# l'application tourner avec une clé devinable — une signature de session
# forgée permettrait de se faire passer pour n'importe quel apprenant.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY est absente de l'environnement. "
        "La renseigner dans le fichier .env à la racine du projet "
        "(voir .env.example). Générer une valeur avec : "
        "uv run python -c \"from django.core.management.utils import "
        "get_random_secret_key as g; print(g())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
#
# Compétence visée : C13 (épreuve E3) — sécurité de l'application
#
# Choix : lecture depuis l'environnement, avec False par défaut. Motivation :
# DEBUG était codé en dur à True. Une exception survenue hors du poste de
# développement affichait alors la trace complète, y compris les variables
# d'environnement — donc la clé secrète et le mot de passe de la base, aux
# yeux de n'importe quel visiteur.
#
# Le défaut est False et non True : une variable oubliée doit dégrader le
# confort de développement, jamais la sécurité de l'exposition.
DEBUG = os.environ.get("DJANGO_DEBUG", "False").strip().lower() in ("1", "true", "oui")

# Logging for debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Compétence visée : C13 (épreuve E3)
#
# Choix : liste lue depuis l'environnement, la boucle locale seule par défaut.
# Motivation : le code autorisait « .ngrok-free.app » en dur, trace d'une
# démonstration exposée par tunnel. Un domaine d'exposition publique inscrit
# dans un fichier versionné survit à la démonstration qui l'a justifié et
# personne ne pense plus à le retirer. Il vit désormais dans .env, avec le
# reste de ce qui dépend de la machine.
ALLOWED_HOSTS = [
    hote.strip()
    for hote in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if hote.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origine.strip()
    for origine in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origine.strip()
]


# Application definition

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'apps.users',
    'apps.courses',
    'apps.quiz',
    'apps.revision',
    'apps.agents.apps.AgentsConfig',
    'apps.chat',
    'apps.rag',
    'apps.tracker',
    'apps.exercises',
    'apps.api_data',
    # Quotas de génération : borne la dépense auprès du fournisseur de modèles
    # avant toute mise en ligne. Voir apps/quotas/service.py.
    'apps.quotas',
    'apps.referentiel',
    'theme',

    # Third-party apps
    'tailwind',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_spectacular',
    'django_browser_reload',
    'channels',
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Service des fichiers statiques par l'application elle-même (C13).
    #
    # Choix : WhiteNoise plutôt qu'un serveur web devant l'application.
    # Motivation : en production, Django refuse de servir les statiques —
    # `runserver --insecure` mis à part — et l'hébergeur retenu envoie le
    # trafic directement au processus applicatif, sans nginx à configurer.
    # Sans ce composant, l'application se déploie et répond, mais sans aucune
    # feuille de style : une panne d'apparence totale que rien ne signale
    # côté serveur.
    #
    # Choix : placé juste après SecurityMiddleware, comme sa documentation
    # l'exige. Plus haut, il court-circuiterait la redirection HTTPS ; plus
    # bas, chaque fichier statique traverserait sessions, authentification et
    # messages pour rien.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Applique à l'interface la langue enregistrée sur le compte.
    #
    # Compétence visée : C17 (épreuve E4)
    #
    # Placé APRÈS AuthenticationMiddleware, sans quoi `request.user` n'existe
    # pas encore et la préférence serait illisible. Il complète
    # LocaleMiddleware plus haut, qui sert les visiteurs non connectés à
    # partir de l'en-tête Accept-Language de leur navigateur.
    #
    # Sans cet intergiciel, le sélecteur de langue du profil enregistrait un
    # choix que rien ne lisait pour l'affichage — un réglage stocké et sans
    # effet, motif documenté par les incidents de ce projet.
    'apps.users.middleware.LangueDeLApprenant',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'eduai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                # Compteur de générations restantes (C13, C17). Calculé
                # paresseusement : les pages qui ne l'affichent pas ne paient
                # aucune requête.
                'apps.quotas.context.quota_generation',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'eduai_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Compétence visée : C17 (épreuve E4) — application web adossée à une base
# Compétence visée : C4 (épreuve E1) — séparation des bases
#
# Choix : PostgreSQL plutôt que SQLite. Motivation : SQLite écrit dans un
# fichier unique verrouillé en écriture, ce qui exclut les accès concurrents
# dont l'application a besoin (WebSockets, tâches d'agents). Il ne connaît par
# ailleurs ni les types natifs ni les contraintes que le jeu de données du
# Bloc 1 utilise, ce qui aurait laissé l'application et le pipeline sur deux
# moteurs différents.
#
# Choix : la base applicative eduai_app est distincte de eduai_data, sur la
# même instance. Motivation : leurs cycles de vie diffèrent — le pipeline
# purge et recharge son jeu de données, et aucune erreur de ciblage ne doit
# pouvoir atteindre les comptes des apprenants. PostgreSQL n'autorise pas de
# requête inter-bases sans extension : l'isolation est structurelle.
# Voir docs/decisions/006.
#
# Choix : les variables d'instance (hôte, port, rôle, mot de passe) sont
# partagées avec le pipeline, seul le nom de la base diffère. Motivation :
# dupliquer le mot de passe dans une seconde variable créerait deux sources
# de vérité à maintenir, donc une occasion de divergence silencieuse.
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
if not POSTGRES_PASSWORD:
    raise ImproperlyConfigured(
        "POSTGRES_PASSWORD est absente de l'environnement. "
        "La renseigner dans le fichier .env à la racine du projet "
        "(voir .env.example). C'est la même valeur que celle utilisée par "
        "le conteneur PostgreSQL de docker-compose.yml."
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DJANGO_DB_NAME", "eduai_app"),
        'USER': os.environ.get("POSTGRES_USER", "eduai"),
        'PASSWORD': POSTGRES_PASSWORD,
        # 127.0.0.1 et non localhost : le conteneur ne publie son port que sur
        # la boucle locale en IPv4, et localhost peut se résoudre en ::1.
        'HOST': os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        # 5433 et non 5432 : le port publié par le conteneur évite le conflit
        # avec une éventuelle instance PostgreSQL installée sur la machine.
        'PORT': os.environ.get("POSTGRES_PORT", "5433"),
    }
}


# Seconde base : le jeu de données collecté par le pipeline, exposé en lecture
# seule par l'API du Bloc 1.
#
# Compétence visée : C5 (épreuve E1) — API REST exposant le jeu de données
# Compétence visée : C4 (épreuve E1) — séparation des deux bases
#
# Choix : un rôle PostgreSQL distinct, ne disposant que du SELECT, plutôt que
# le rôle propriétaire. Motivation : le routeur Django refuse déjà les
# écritures et les vues n'exposent aucune route d'écriture, mais ces deux
# garanties vivent dans le code. Le rôle, lui, tient même si le code se trompe.
# Voir docs/decisions/012.
EDUAI_DATA_PASSWORD = os.environ.get("EDUAI_DATA_PASSWORD")
if not EDUAI_DATA_PASSWORD:
    raise ImproperlyConfigured(
        "EDUAI_DATA_PASSWORD est absente de l'environnement. C'est le mot de "
        "passe du rôle PostgreSQL en lecture seule utilisé par l'API du jeu "
        "de données. Le renseigner dans .env (voir .env.example)."
    )

DATABASES["eduai_data"] = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": os.environ.get("POSTGRES_DB", "eduai_data"),
    "USER": os.environ.get("EDUAI_DATA_USER", "eduai_lecture"),
    "PASSWORD": EDUAI_DATA_PASSWORD,
    "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
    "PORT": os.environ.get("POSTGRES_PORT", "5433"),
}

# Sans routeur, Django interrogerait `default` pour les modèles de api_data et
# n'y trouverait aucune des treize tables du jeu de données.
DATABASE_ROUTERS = ["apps.api_data.routeurs.RouteurJeuDonnees"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.KodaUser"

# Custom authentication backend
AUTHENTICATION_BACKENDS = [
    'apps.users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Authentication redirect URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/courses/generator/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Langue par défaut du service.
#
# Compétence visée : C17 (épreuve E4) — application web
#
# Choix : le français. Motivation : l'organisme de formation et ses apprenants
# sont francophones, et les seules traductions du projet allaient jusqu'ici du
# français vers... rien — le catalogue `fr` existait, mais LANGUAGE_CODE valait
# 'en', si bien qu'aucune traduction n'était jamais appliquée. L'interface
# affichait donc ses chaînes sources, en anglais, à côté des quelques messages
# écrits en français : c'est l'origine du mélange des deux langues sur une même
# page.
#
# Cette valeur n'est qu'un défaut : LocaleMiddleware la remplace par la langue
# choisie par la personne connectée, quand elle en a choisi une.
LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
]

# Catalogues de traduction du projet.
#
# Compétence visée : C17 (épreuve E4)
#
# Un seul emplacement, à la racine, plutôt qu'un catalogue par application.
# Motivation : le projet n'a pas d'application réutilisable hors de lui, et
# disperser les traductions ferait chercher dans huit dossiers la chaîne qu'on
# veut corriger. Les chemins de LOCALE_PATHS ont priorité sur les catalogues
# d'application, ce qui rend l'emplacement unique et non ambigu.
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Toujours défini pour collectstatic

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Folder for global static files
]

# Stockage des statiques collectés.
#
# Compétence visée : C13 (épreuve E3)
#
# Choix : le stockage compressé et empreinté de WhiteNoise, et seulement quand
# DEBUG vaut False. Motivation : l'empreinte dans le nom de fichier
# (`app.4f2a1c.css`) permet un cache navigateur d'un an sans risquer de servir
# une version périmée après un déploiement. Activé en développement, il
# obligerait à relancer `collectstatic` après chaque retouche de feuille de
# style — et une gêne quotidienne finit par être désactivée partout.
#
# La classe de stockage est définie dans `eduai_project/statiques.py`, qui
# porte le détail : elle tolère les références à des fichiers absents du
# manifeste plutôt que d'en faire une erreur 500 en pleine démonstration.
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "eduai_project.statiques.StockageStatiquesTolerant",
        },
    }

# Static file finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files (User-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/auth/login/'
LOGIN_URL = '/auth/login/'            # @login_required protection

# --- API REST du jeu de données (C5, Bloc 1) ---
#
# Compétence visée : C5 (épreuve E1)
# Compétence visée : C13 (épreuve E3) — sécurité de l'API
#
# Ces réglages s'appliquent à l'API du jeu de données. L'API du service IA
# (C9, Bloc 2) vivra dans un service FastAPI distinct, avec ses propres
# réglages : les deux périmètres ne partagent pas leur configuration.
REST_FRAMEWORK = {
    # --- Authentification ---
    #
    # Choix : jeton porteur, doublé de la session pour l'interface navigable.
    # Motivation : un consommateur du jeu de données est le plus souvent un
    # script, pour lequel la session par cookie n'a pas de sens. La session
    # reste utile à la documentation interactive, consultée depuis un
    # navigateur déjà authentifié.
    #
    # L'authentification par jeton répond à OWASP API2, « Broken
    # Authentication » : chaque jeton est révocable individuellement, sans
    # toucher au mot de passe du compte.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],

    # --- Autorisation ---
    #
    # Choix : authentification exigée partout, sans exception. Motivation :
    # le corpus agrège des sources dont les licences imposent des conditions de
    # redistribution. L'exposer anonymement reviendrait à le republier sans
    # savoir à qui, alors que les conditions de plusieurs sources engagent
    # celui qui rediffuse. C'est aussi la réponse à OWASP API1, « Broken
    # Object Level Authorization » : aucun objet n'est atteignable sans compte.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    # --- Limitation de débit ---
    #
    # Réponse à OWASP API4, « Unrestricted Resource Consumption ». Les
    # anonymes sont bridés bas : ils ne peuvent de toute façon qu'atteindre la
    # documentation et se voir refuser les données.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/hour",
        "user": "1000/day",
    },

    # --- Pagination ---
    #
    # Aucun point de terminaison de collection ne renvoie tout. Voir
    # apps/api_data/pagination.py pour le plafond et sa motivation.
    "DEFAULT_PAGINATION_CLASS": "apps.api_data.pagination.PaginationJeuDonnees",
    "PAGE_SIZE": 20,

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],

    # Le schéma OpenAPI est engendré depuis le code par drf-spectacular.
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Documentation OpenAPI engendrée depuis le code.
#
# Compétence visée : C5 (épreuve E1) — documentation de l'API
SPECTACULAR_SETTINGS = {
    "TITLE": "EduAI Tutor — API du jeu de données",
    "DESCRIPTION": (
        "API REST exposant en lecture seule le corpus collecté par le "
        "pipeline de données (Bloc 1, compétence C5).\n\n"
        "Le corpus agrège cinq types de sources : service web, scraping, "
        "fichiers, base de données et système big data.\n\n"
        "**Lecture seule.** Le jeu de données est alimenté par le pipeline, "
        "jamais par cette API. Aucune route d'écriture n'est exposée, et la "
        "connexion utilise un rôle PostgreSQL ne disposant que du SELECT.\n\n"
        "**Filtrage par licence.** Seuls les documents dont la licence "
        "autorise la redistribution sont exposés. Les documents d'origine non "
        "vérifiée et les productions d'apprenants en sont exclus par "
        "construction, quel que soit le point de terminaison interrogé.\n\n"
        "**Attribution.** Plusieurs licences du corpus exigent de créditer "
        "l'auteur. Le champ `attribution_requise` le signale, et `url_source` "
        "pointe vers la page où la source crédite elle-même son auteur."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Le schéma ne décrit que l'API du jeu de données : les vues de
    # l'application web n'ont pas à y figurer.
    "SCHEMA_PATH_PREFIX": "/api/dataset",
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
}


# Channels configuration
ASGI_APPLICATION = 'eduai_project.asgi.application'

# WebSocket configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Channel layers configuration for WebSockets

# --- Réglages de sécurité du transport ---
#
# Compétence visée : C13 (épreuve E3) — sécurité de l'application
#
# Choix : ces réglages ne s'activent que lorsque DEBUG vaut False.
# Motivation : SECURE_SSL_REDIRECT et les cookies sécurisés exigent HTTPS. Le
# serveur de développement sert en clair sur http://127.0.0.1 ; les activer en
# permanence rendrait l'application inutilisable en local — et ce qui gêne au
# quotidien finit par être désactivé globalement plutôt que conditionnellement.
if not DEBUG:
    # Redirection systématique vers HTTPS. Sans elle, une première requête en
    # clair transporte le cookie de session avant toute chance de le protéger.
    SECURE_SSL_REDIRECT = True

    # HSTS : le navigateur refuse le HTTP pour ce domaine pendant un an, même
    # si l'utilisateur tape l'adresse à la main. Contre-mesure à l'interception
    # de la toute première requête, que la seule redirection laisse passer.
    #
    # Un an, valeur exigée pour un éventuel préchargement. À n'activer qu'une
    # fois le certificat en place : un domaine servi en clair devient
    # inatteignable pour la durée annoncée.
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Les cookies d'authentification et de protection CSRF ne partent plus sur
    # un canal en clair. Sans ces deux réglages, une seule requête HTTP
    # résiduelle — une image, une redirection — suffit à divulguer la session.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Le cookie de session n'est pas joint aux requêtes venues d'un autre site,
    # sauf navigation de premier niveau : protection CSRF complémentaire.
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    # Derrière un terminateur TLS (tunnel, proxy inverse), Django voit du HTTP
    # et SECURE_SSL_REDIRECT boucle indéfiniment. Cet en-tête lui indique de
    # faire confiance au proxy.
    #
    # Activé uniquement sur déclaration explicite : croire cet en-tête sans
    # proxy devant permettrait à n'importe quel client de l'envoyer lui-même
    # et de contourner la redirection.
    if os.environ.get("DJANGO_DERRIERE_PROXY", "False").strip().lower() in ("1", "true", "oui"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
