# Generated by Django 5.2.12 on 2026-08-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('pk', models.CompositePrimaryKey('document', 'mot_cle', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('code_type_source', models.CharField(max_length=20)),
                ('identifiant_source', models.CharField(max_length=120)),
                ('attribution_requise', models.BooleanField()),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('url_source', models.CharField(max_length=500, null=True)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], max_length=2)),
                ('extrait_le', models.DateTimeField()),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-extrait_le', 'id_document'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id_extraction', models.AutoField(primary_key=True, serialize=False)),
                ('horodatage_debut', models.DateTimeField()),
                ('duree_secondes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=10)),
                ('nb_enregistrements', models.IntegerField()),
                ('nb_erreurs', models.IntegerField()),
                ('fichier_sortie', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'extraction',
                'ordering': ['-horodatage_debut'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('code_licence', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
                ('url_texte', models.CharField(max_length=255, null=True)),
                ('redistribution_autorisee', models.BooleanField()),
                ('attribution_requise', models.BooleanField()),
                ('mention_copyright', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'licence',
                'ordering': ['code_licence'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('code_mot_cle', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'mot-clé',
                'verbose_name_plural': 'mots-clés',
                'db_table': 'mot_cle',
                'ordering': ['code_mot_cle'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('code_source', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('url_racine', models.CharField(max_length=255, null=True)),
                ('contraintes_acces', models.TextField()),
                ('duree_conservation_jours', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'source',
                'ordering': ['code_source'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeSource',
            fields=[
                ('code_type_source', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'type de source',
                'verbose_name_plural': 'types de source',
                'db_table': 'type_source',
                'ordering': ['code_type_source'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentApiRest',
            fields=[
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail_api_rest', serialize=False, to='api_data.document')),
                ('code_type_source', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('nombre_reponses', models.SmallIntegerField()),
                ('nombre_vues', models.IntegerField()),
                ('cree_le', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_api_rest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentBaseDonnees',
            fields=[
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail_base_donnees', serialize=False, to='api_data.document')),
                ('code_type_source', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'document_base_donnees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentBigData',
            fields=[
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail_big_data', serialize=False, to='api_data.document')),
                ('code_type_source', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'document_big_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentFichier',
            fields=[
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail_fichier', serialize=False, to='api_data.document')),
                ('code_type_source', models.CharField(max_length=20)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=10)),
                ('module_pedagogique', models.CharField(max_length=50)),
                ('index_section', models.SmallIntegerField()),
                ('origine_declaree', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'document_fichier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentWeb',
            fields=[
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail_web', serialize=False, to='api_data.document')),
                ('code_type_source', models.CharField(max_length=20)),
                ('page', models.CharField(max_length=255)),
                ('ancre_section', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'document_web',
                'managed': False,
            },
        ),
    ]
